server:
  port: 8084

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
  profiles:
    active: native