server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vitmvit/spring-cloud-service.git
          username: vitmvit
          password: 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
          default-label: main
          search-paths: "{application}"