spring:
  application:
    name: auth-service
  logging:
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO

security:
  jwt:
    token:
      secret-key: "secretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkeysecretkey"

starter:
  logging:
    enabled: true
  handler:
    enabled: true