server:
  port: 8083

spring:
  config:
    import: optional:configserver:http://spring-cloud-service:7777/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/news_management
    username: root
    password: root
  redis:
    port: 6379
    host: redis
    cluster:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO

springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc/