spring:
  application:
    name: comments-service
  redis:
    port: 6379
    host: localhost
    cluster:
      enabled: true
  logging:
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO

cache:
  algorithm: lru
  capacity: 15

starter:
  logging:
    enabled: true
  handler:
    enabled: true