server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://spring-cloud-service:7777/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/news_management
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO

springdoc:
  swagger-ui:
    enabled: true
    path: /api/doc/

feign:
  auth-service:
    value: authService
    url: http://auth-service:8081/api/auth
  news-service:
    value: newsService
    url-news: http://news-service:8082/api/news
    url-comments: http://news-service:8082/api/comments