spring:
  application:
    name: core-service
  liquibase:
    enabled: true
    change-log: changelog-master.xml
  logging:
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO

starter:
  logging:
    enabled: true
  handler:
    enabled: true

feign:
  auth-service:
    value: authService
    url: http://localhost:8081/api/auth
  news-service:
    value: newsService
    url-news: http://localhost:8082/api/news
  comment-service:
    value: commentService
    url-comments: http://localhost:8083/api/comments