spring:
  application:
    name: news-service
  redis:
    port: 6379
    host: localhost
    cluster:
      enabled: true
  logging:
    level:
      org.springframework.web: INFO
      guru.springframework.controllers: INFO
      org.hibernate: INFO

starter:
  logging:
    enabled: true
  handler:
    enabled: true

cache:
  algorithm: lfu
  capacity: 15

feign:
  comments-service:
    value: commentService
    url: http://localhost:8083/api/comments